// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BulkAddResponse.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class BulkAddResponseProtocol {
  private BulkAddResponseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class BulkAddResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use BulkAddResponse.newBuilder() to construct.
    private BulkAddResponse() {
      initFields();
    }
    private BulkAddResponse(boolean noInit) {}
    
    private static final BulkAddResponse defaultInstance;
    public static BulkAddResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public BulkAddResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_fieldAccessorTable;
    }
    
    // optional .com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponse keyExceptionPackage = 1;
    public static final int KEYEXCEPTIONPACKAGE_FIELD_NUMBER = 1;
    private boolean hasKeyExceptionPackage;
    private com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse keyExceptionPackage_;
    public boolean hasKeyExceptionPackage() { return hasKeyExceptionPackage; }
    public com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse getKeyExceptionPackage() { return keyExceptionPackage_; }
    
    private void initFields() {
      keyExceptionPackage_ = com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKeyExceptionPackage()) {
        output.writeMessage(1, getKeyExceptionPackage());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKeyExceptionPackage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getKeyExceptionPackage());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.getDefaultInstance()) return this;
        if (other.hasKeyExceptionPackage()) {
          mergeKeyExceptionPackage(other.getKeyExceptionPackage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.Builder subBuilder = com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.newBuilder();
              if (hasKeyExceptionPackage()) {
                subBuilder.mergeFrom(getKeyExceptionPackage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setKeyExceptionPackage(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponse keyExceptionPackage = 1;
      public boolean hasKeyExceptionPackage() {
        return result.hasKeyExceptionPackage();
      }
      public com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse getKeyExceptionPackage() {
        return result.getKeyExceptionPackage();
      }
      public Builder setKeyExceptionPackage(com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasKeyExceptionPackage = true;
        result.keyExceptionPackage_ = value;
        return this;
      }
      public Builder setKeyExceptionPackage(com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.Builder builderForValue) {
        result.hasKeyExceptionPackage = true;
        result.keyExceptionPackage_ = builderForValue.build();
        return this;
      }
      public Builder mergeKeyExceptionPackage(com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse value) {
        if (result.hasKeyExceptionPackage() &&
            result.keyExceptionPackage_ != com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.getDefaultInstance()) {
          result.keyExceptionPackage_ =
            com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.newBuilder(result.keyExceptionPackage_).mergeFrom(value).buildPartial();
        } else {
          result.keyExceptionPackage_ = value;
        }
        result.hasKeyExceptionPackage = true;
        return this;
      }
      public Builder clearKeyExceptionPackage() {
        result.hasKeyExceptionPackage = false;
        result.keyExceptionPackage_ = com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.KeyExceptionPackageResponse.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.BulkAddResponse)
    }
    
    static {
      defaultInstance = new BulkAddResponse(true);
      com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.BulkAddResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025BulkAddResponse.proto\022\'com.alachisoft." +
      "tayzgrid.common.protobuf\032!KeyExceptionPa" +
      "ckageResponse.proto\"t\n\017BulkAddResponse\022a" +
      "\n\023keyExceptionPackage\030\001 \001(\0132D.com.alachi" +
      "soft.tayzgrid.common.protobuf.KeyExcepti" +
      "onPackageResponseB\031B\027BulkAddResponseProt" +
      "ocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_BulkAddResponse_descriptor,
              new java.lang.String[] { "KeyExceptionPackage", },
              com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.class,
              com.alachisoft.tayzgrid.common.protobuf.BulkAddResponseProtocol.BulkAddResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alachisoft.tayzgrid.common.protobuf.KeyExceptionPackageResponseProtocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
