// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DeleteCommand.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class DeleteCommandProtocol {
  private DeleteCommandProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class DeleteCommand extends
      com.google.protobuf.GeneratedMessage {
    // Use DeleteCommand.newBuilder() to construct.
    private DeleteCommand() {
      initFields();
    }
    private DeleteCommand(boolean noInit) {}
    
    private static final DeleteCommand defaultInstance;
    public static DeleteCommand getDefaultInstance() {
      return defaultInstance;
    }
    
    public DeleteCommand getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_fieldAccessorTable;
    }
    
    // optional bytes key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // optional int64 requestId = 2;
    public static final int REQUESTID_FIELD_NUMBER = 2;
    private boolean hasRequestId;
    private long requestId_ = 0L;
    public boolean hasRequestId() { return hasRequestId; }
    public long getRequestId() { return requestId_; }
    
    // optional int32 flag = 3;
    public static final int FLAG_FIELD_NUMBER = 3;
    private boolean hasFlag;
    private int flag_ = 0;
    public boolean hasFlag() { return hasFlag; }
    public int getFlag() { return flag_; }
    
    // optional bool isAsync = 4;
    public static final int ISASYNC_FIELD_NUMBER = 4;
    private boolean hasIsAsync;
    private boolean isAsync_ = false;
    public boolean hasIsAsync() { return hasIsAsync; }
    public boolean getIsAsync() { return isAsync_; }
    
    // optional sint32 datasourceItemRemovedCallbackId = 5;
    public static final int DATASOURCEITEMREMOVEDCALLBACKID_FIELD_NUMBER = 5;
    private boolean hasDatasourceItemRemovedCallbackId;
    private int datasourceItemRemovedCallbackId_ = 0;
    public boolean hasDatasourceItemRemovedCallbackId() { return hasDatasourceItemRemovedCallbackId; }
    public int getDatasourceItemRemovedCallbackId() { return datasourceItemRemovedCallbackId_; }
    
    // optional string lockId = 6;
    public static final int LOCKID_FIELD_NUMBER = 6;
    private boolean hasLockId;
    private java.lang.String lockId_ = "";
    public boolean hasLockId() { return hasLockId; }
    public java.lang.String getLockId() { return lockId_; }
    
    // optional int32 lockAccessType = 7;
    public static final int LOCKACCESSTYPE_FIELD_NUMBER = 7;
    private boolean hasLockAccessType;
    private int lockAccessType_ = 0;
    public boolean hasLockAccessType() { return hasLockAccessType; }
    public int getLockAccessType() { return lockAccessType_; }
    
    // optional uint64 version = 8;
    public static final int VERSION_FIELD_NUMBER = 8;
    private boolean hasVersion;
    private long version_ = 0L;
    public boolean hasVersion() { return hasVersion; }
    public long getVersion() { return version_; }
    
    // optional string providerName = 9;
    public static final int PROVIDERNAME_FIELD_NUMBER = 9;
    private boolean hasProviderName;
    private java.lang.String providerName_ = "";
    public boolean hasProviderName() { return hasProviderName; }
    public java.lang.String getProviderName() { return providerName_; }
    
    // optional bool compareOld = 10;
    public static final int COMPAREOLD_FIELD_NUMBER = 10;
    private boolean hasCompareOld;
    private boolean compareOld_ = false;
    public boolean hasCompareOld() { return hasCompareOld; }
    public boolean getCompareOld() { return compareOld_; }
    
    // optional int32 oldValueFlag = 11;
    public static final int OLDVALUEFLAG_FIELD_NUMBER = 11;
    private boolean hasOldValueFlag;
    private int oldValueFlag_ = 0;
    public boolean hasOldValueFlag() { return hasOldValueFlag; }
    public int getOldValueFlag() { return oldValueFlag_; }
    
    // repeated bytes oldValue = 12;
    public static final int OLDVALUE_FIELD_NUMBER = 12;
    private java.util.List<com.google.protobuf.ByteString> oldValue_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getOldValueList() {
      return oldValue_;
    }
    public int getOldValueCount() { return oldValue_.size(); }
    public com.google.protobuf.ByteString getOldValue(int index) {
      return oldValue_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasKey()) {
        output.writeBytes(1, getKey());
      }
      if (hasRequestId()) {
        output.writeInt64(2, getRequestId());
      }
      if (hasFlag()) {
        output.writeInt32(3, getFlag());
      }
      if (hasIsAsync()) {
        output.writeBool(4, getIsAsync());
      }
      if (hasDatasourceItemRemovedCallbackId()) {
        output.writeSInt32(5, getDatasourceItemRemovedCallbackId());
      }
      if (hasLockId()) {
        output.writeString(6, getLockId());
      }
      if (hasLockAccessType()) {
        output.writeInt32(7, getLockAccessType());
      }
      if (hasVersion()) {
        output.writeUInt64(8, getVersion());
      }
      if (hasProviderName()) {
        output.writeString(9, getProviderName());
      }
      if (hasCompareOld()) {
        output.writeBool(10, getCompareOld());
      }
      if (hasOldValueFlag()) {
        output.writeInt32(11, getOldValueFlag());
      }
      for (com.google.protobuf.ByteString element : getOldValueList()) {
        output.writeBytes(12, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getKey());
      }
      if (hasRequestId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getRequestId());
      }
      if (hasFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getFlag());
      }
      if (hasIsAsync()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getIsAsync());
      }
      if (hasDatasourceItemRemovedCallbackId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(5, getDatasourceItemRemovedCallbackId());
      }
      if (hasLockId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getLockId());
      }
      if (hasLockAccessType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getLockAccessType());
      }
      if (hasVersion()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, getVersion());
      }
      if (hasProviderName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getProviderName());
      }
      if (hasCompareOld()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, getCompareOld());
      }
      if (hasOldValueFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, getOldValueFlag());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getOldValueList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getOldValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.oldValue_ != java.util.Collections.EMPTY_LIST) {
          result.oldValue_ =
            java.util.Collections.unmodifiableList(result.oldValue_);
        }
        com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (other.hasIsAsync()) {
          setIsAsync(other.getIsAsync());
        }
        if (other.hasDatasourceItemRemovedCallbackId()) {
          setDatasourceItemRemovedCallbackId(other.getDatasourceItemRemovedCallbackId());
        }
        if (other.hasLockId()) {
          setLockId(other.getLockId());
        }
        if (other.hasLockAccessType()) {
          setLockAccessType(other.getLockAccessType());
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasProviderName()) {
          setProviderName(other.getProviderName());
        }
        if (other.hasCompareOld()) {
          setCompareOld(other.getCompareOld());
        }
        if (other.hasOldValueFlag()) {
          setOldValueFlag(other.getOldValueFlag());
        }
        if (!other.oldValue_.isEmpty()) {
          if (result.oldValue_.isEmpty()) {
            result.oldValue_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.oldValue_.addAll(other.oldValue_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setKey(input.readBytes());
              break;
            }
            case 16: {
              setRequestId(input.readInt64());
              break;
            }
            case 24: {
              setFlag(input.readInt32());
              break;
            }
            case 32: {
              setIsAsync(input.readBool());
              break;
            }
            case 40: {
              setDatasourceItemRemovedCallbackId(input.readSInt32());
              break;
            }
            case 50: {
              setLockId(input.readString());
              break;
            }
            case 56: {
              setLockAccessType(input.readInt32());
              break;
            }
            case 64: {
              setVersion(input.readUInt64());
              break;
            }
            case 74: {
              setProviderName(input.readString());
              break;
            }
            case 80: {
              setCompareOld(input.readBool());
              break;
            }
            case 88: {
              setOldValueFlag(input.readInt32());
              break;
            }
            case 98: {
              addOldValue(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional bytes key = 1;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional int64 requestId = 2;
      public boolean hasRequestId() {
        return result.hasRequestId();
      }
      public long getRequestId() {
        return result.getRequestId();
      }
      public Builder setRequestId(long value) {
        result.hasRequestId = true;
        result.requestId_ = value;
        return this;
      }
      public Builder clearRequestId() {
        result.hasRequestId = false;
        result.requestId_ = 0L;
        return this;
      }
      
      // optional int32 flag = 3;
      public boolean hasFlag() {
        return result.hasFlag();
      }
      public int getFlag() {
        return result.getFlag();
      }
      public Builder setFlag(int value) {
        result.hasFlag = true;
        result.flag_ = value;
        return this;
      }
      public Builder clearFlag() {
        result.hasFlag = false;
        result.flag_ = 0;
        return this;
      }
      
      // optional bool isAsync = 4;
      public boolean hasIsAsync() {
        return result.hasIsAsync();
      }
      public boolean getIsAsync() {
        return result.getIsAsync();
      }
      public Builder setIsAsync(boolean value) {
        result.hasIsAsync = true;
        result.isAsync_ = value;
        return this;
      }
      public Builder clearIsAsync() {
        result.hasIsAsync = false;
        result.isAsync_ = false;
        return this;
      }
      
      // optional sint32 datasourceItemRemovedCallbackId = 5;
      public boolean hasDatasourceItemRemovedCallbackId() {
        return result.hasDatasourceItemRemovedCallbackId();
      }
      public int getDatasourceItemRemovedCallbackId() {
        return result.getDatasourceItemRemovedCallbackId();
      }
      public Builder setDatasourceItemRemovedCallbackId(int value) {
        result.hasDatasourceItemRemovedCallbackId = true;
        result.datasourceItemRemovedCallbackId_ = value;
        return this;
      }
      public Builder clearDatasourceItemRemovedCallbackId() {
        result.hasDatasourceItemRemovedCallbackId = false;
        result.datasourceItemRemovedCallbackId_ = 0;
        return this;
      }
      
      // optional string lockId = 6;
      public boolean hasLockId() {
        return result.hasLockId();
      }
      public java.lang.String getLockId() {
        return result.getLockId();
      }
      public Builder setLockId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLockId = true;
        result.lockId_ = value;
        return this;
      }
      public Builder clearLockId() {
        result.hasLockId = false;
        result.lockId_ = getDefaultInstance().getLockId();
        return this;
      }
      
      // optional int32 lockAccessType = 7;
      public boolean hasLockAccessType() {
        return result.hasLockAccessType();
      }
      public int getLockAccessType() {
        return result.getLockAccessType();
      }
      public Builder setLockAccessType(int value) {
        result.hasLockAccessType = true;
        result.lockAccessType_ = value;
        return this;
      }
      public Builder clearLockAccessType() {
        result.hasLockAccessType = false;
        result.lockAccessType_ = 0;
        return this;
      }
      
      // optional uint64 version = 8;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public long getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(long value) {
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = 0L;
        return this;
      }
      
      // optional string providerName = 9;
      public boolean hasProviderName() {
        return result.hasProviderName();
      }
      public java.lang.String getProviderName() {
        return result.getProviderName();
      }
      public Builder setProviderName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProviderName = true;
        result.providerName_ = value;
        return this;
      }
      public Builder clearProviderName() {
        result.hasProviderName = false;
        result.providerName_ = getDefaultInstance().getProviderName();
        return this;
      }
      
      // optional bool compareOld = 10;
      public boolean hasCompareOld() {
        return result.hasCompareOld();
      }
      public boolean getCompareOld() {
        return result.getCompareOld();
      }
      public Builder setCompareOld(boolean value) {
        result.hasCompareOld = true;
        result.compareOld_ = value;
        return this;
      }
      public Builder clearCompareOld() {
        result.hasCompareOld = false;
        result.compareOld_ = false;
        return this;
      }
      
      // optional int32 oldValueFlag = 11;
      public boolean hasOldValueFlag() {
        return result.hasOldValueFlag();
      }
      public int getOldValueFlag() {
        return result.getOldValueFlag();
      }
      public Builder setOldValueFlag(int value) {
        result.hasOldValueFlag = true;
        result.oldValueFlag_ = value;
        return this;
      }
      public Builder clearOldValueFlag() {
        result.hasOldValueFlag = false;
        result.oldValueFlag_ = 0;
        return this;
      }
      
      // repeated bytes oldValue = 12;
      public java.util.List<com.google.protobuf.ByteString> getOldValueList() {
        return java.util.Collections.unmodifiableList(result.oldValue_);
      }
      public int getOldValueCount() {
        return result.getOldValueCount();
      }
      public com.google.protobuf.ByteString getOldValue(int index) {
        return result.getOldValue(index);
      }
      public Builder setOldValue(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.oldValue_.set(index, value);
        return this;
      }
      public Builder addOldValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.oldValue_.isEmpty()) {
          result.oldValue_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.oldValue_.add(value);
        return this;
      }
      public Builder addAllOldValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.oldValue_.isEmpty()) {
          result.oldValue_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.oldValue_);
        return this;
      }
      public Builder clearOldValue() {
        result.oldValue_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.DeleteCommand)
    }
    
    static {
      defaultInstance = new DeleteCommand(true);
      com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.DeleteCommand)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023DeleteCommand.proto\022\'com.alachisoft.ta" +
      "yzgrid.common.protobuf\"\202\002\n\rDeleteCommand" +
      "\022\013\n\003key\030\001 \001(\014\022\021\n\trequestId\030\002 \001(\003\022\014\n\004flag" +
      "\030\003 \001(\005\022\017\n\007isAsync\030\004 \001(\010\022\'\n\037datasourceIte" +
      "mRemovedCallbackId\030\005 \001(\021\022\016\n\006lockId\030\006 \001(\t" +
      "\022\026\n\016lockAccessType\030\007 \001(\005\022\017\n\007version\030\010 \001(" +
      "\004\022\024\n\014providerName\030\t \001(\t\022\022\n\ncompareOld\030\n " +
      "\001(\010\022\024\n\014oldValueFlag\030\013 \001(\005\022\020\n\010oldValue\030\014 " +
      "\003(\014B\027B\025DeleteCommandProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_DeleteCommand_descriptor,
              new java.lang.String[] { "Key", "RequestId", "Flag", "IsAsync", "DatasourceItemRemovedCallbackId", "LockId", "LockAccessType", "Version", "ProviderName", "CompareOld", "OldValueFlag", "OldValue", },
              com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.class,
              com.alachisoft.tayzgrid.common.protobuf.DeleteCommandProtocol.DeleteCommand.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
