// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EventInfo.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class EventInfoProtocol {
  private EventInfoProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class EventInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use EventInfo.newBuilder() to construct.
    private EventInfo() {
      initFields();
    }
    private EventInfo(boolean noInit) {}
    
    private static final EventInfo defaultInstance;
    public static EventInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_fieldAccessorTable;
    }
    
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      ITEM_REMOVED_CALLBACK(0, 1),
      ITEM_UPDATED_CALLBACK(1, 2),
      ITEM_ADDED_EVENT(2, 3),
      ITEM_REMOVED_EVENT(3, 4),
      ITEM_UPDATED_EVENT(4, 5),
      CACHE_CLEARED_EVENT(5, 6),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static EventType valueOf(int value) {
        switch (value) {
          case 1: return ITEM_REMOVED_CALLBACK;
          case 2: return ITEM_UPDATED_CALLBACK;
          case 3: return ITEM_ADDED_EVENT;
          case 4: return ITEM_REMOVED_EVENT;
          case 5: return ITEM_UPDATED_EVENT;
          case 6: return CACHE_CLEARED_EVENT;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number)
      ;        }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final EventType[] VALUES = {
        ITEM_REMOVED_CALLBACK, ITEM_UPDATED_CALLBACK, ITEM_ADDED_EVENT, ITEM_REMOVED_EVENT, ITEM_UPDATED_EVENT, CACHE_CLEARED_EVENT, 
      };
      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      static {
        com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.getDescriptor();
      }
      
      // @@protoc_insertion_point(enum_scope:com.alachisoft.tayzgrid.common.protobuf.EventInfo.EventType)
    }
    
    // optional sint32 callbackId = 1;
    public static final int CALLBACKID_FIELD_NUMBER = 1;
    private boolean hasCallbackId;
    private int callbackId_ = 0;
    public boolean hasCallbackId() { return hasCallbackId; }
    public int getCallbackId() { return callbackId_; }
    
    // optional bytes key = 2;
    public static final int KEY_FIELD_NUMBER = 2;
    private boolean hasKey;
    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasKey() { return hasKey; }
    public com.google.protobuf.ByteString getKey() { return key_; }
    
    // optional int32 itemRemoveReason = 3;
    public static final int ITEMREMOVEREASON_FIELD_NUMBER = 3;
    private boolean hasItemRemoveReason;
    private int itemRemoveReason_ = 0;
    public boolean hasItemRemoveReason() { return hasItemRemoveReason; }
    public int getItemRemoveReason() { return itemRemoveReason_; }
    
    // optional int32 flag = 4;
    public static final int FLAG_FIELD_NUMBER = 4;
    private boolean hasFlag;
    private int flag_ = 0;
    public boolean hasFlag() { return hasFlag; }
    public int getFlag() { return flag_; }
    
    // repeated bytes value = 5;
    public static final int VALUE_FIELD_NUMBER = 5;
    private java.util.List<com.google.protobuf.ByteString> value_ =
      java.util.Collections.emptyList();
    public java.util.List<com.google.protobuf.ByteString> getValueList() {
      return value_;
    }
    public int getValueCount() { return value_.size(); }
    public com.google.protobuf.ByteString getValue(int index) {
      return value_.get(index);
    }
    
    // optional .com.alachisoft.tayzgrid.common.protobuf.EventId eventId = 6;
    public static final int EVENTID_FIELD_NUMBER = 6;
    private boolean hasEventId;
    private com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId eventId_;
    public boolean hasEventId() { return hasEventId; }
    public com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId getEventId() { return eventId_; }
    
    // optional int32 changeType = 7;
    public static final int CHANGETYPE_FIELD_NUMBER = 7;
    private boolean hasChangeType;
    private int changeType_ = 0;
    public boolean hasChangeType() { return hasChangeType; }
    public int getChangeType() { return changeType_; }
    
    // optional string queryId = 8;
    public static final int QUERYID_FIELD_NUMBER = 8;
    private boolean hasQueryId;
    private java.lang.String queryId_ = "";
    public boolean hasQueryId() { return hasQueryId; }
    public java.lang.String getQueryId() { return queryId_; }
    
    // optional .com.alachisoft.tayzgrid.common.protobuf.EventInfo.EventType eventType = 9;
    public static final int EVENTTYPE_FIELD_NUMBER = 9;
    private boolean hasEventType;
    private com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType eventType_;
    public boolean hasEventType() { return hasEventType; }
    public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType getEventType() { return eventType_; }
    
    private void initFields() {
      eventId_ = com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.getDefaultInstance();
      eventType_ = com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType.ITEM_REMOVED_CALLBACK;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCallbackId()) {
        output.writeSInt32(1, getCallbackId());
      }
      if (hasKey()) {
        output.writeBytes(2, getKey());
      }
      if (hasItemRemoveReason()) {
        output.writeInt32(3, getItemRemoveReason());
      }
      if (hasFlag()) {
        output.writeInt32(4, getFlag());
      }
      for (com.google.protobuf.ByteString element : getValueList()) {
        output.writeBytes(5, element);
      }
      if (hasEventId()) {
        output.writeMessage(6, getEventId());
      }
      if (hasChangeType()) {
        output.writeInt32(7, getChangeType());
      }
      if (hasQueryId()) {
        output.writeString(8, getQueryId());
      }
      if (hasEventType()) {
        output.writeEnum(9, getEventType().getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCallbackId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, getCallbackId());
      }
      if (hasKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getKey());
      }
      if (hasItemRemoveReason()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getItemRemoveReason());
      }
      if (hasFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getFlag());
      }
      {
        int dataSize = 0;
        for (com.google.protobuf.ByteString element : getValueList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      if (hasEventId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getEventId());
      }
      if (hasChangeType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getChangeType());
      }
      if (hasQueryId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getQueryId());
      }
      if (hasEventType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(9, getEventType().getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.value_ != java.util.Collections.EMPTY_LIST) {
          result.value_ =
            java.util.Collections.unmodifiableList(result.value_);
        }
        com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.getDefaultInstance()) return this;
        if (other.hasCallbackId()) {
          setCallbackId(other.getCallbackId());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasItemRemoveReason()) {
          setItemRemoveReason(other.getItemRemoveReason());
        }
        if (other.hasFlag()) {
          setFlag(other.getFlag());
        }
        if (!other.value_.isEmpty()) {
          if (result.value_.isEmpty()) {
            result.value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
          }
          result.value_.addAll(other.value_);
        }
        if (other.hasEventId()) {
          mergeEventId(other.getEventId());
        }
        if (other.hasChangeType()) {
          setChangeType(other.getChangeType());
        }
        if (other.hasQueryId()) {
          setQueryId(other.getQueryId());
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setCallbackId(input.readSInt32());
              break;
            }
            case 18: {
              setKey(input.readBytes());
              break;
            }
            case 24: {
              setItemRemoveReason(input.readInt32());
              break;
            }
            case 32: {
              setFlag(input.readInt32());
              break;
            }
            case 42: {
              addValue(input.readBytes());
              break;
            }
            case 50: {
              com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.Builder subBuilder = com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.newBuilder();
              if (hasEventId()) {
                subBuilder.mergeFrom(getEventId());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setEventId(subBuilder.buildPartial());
              break;
            }
            case 56: {
              setChangeType(input.readInt32());
              break;
            }
            case 66: {
              setQueryId(input.readString());
              break;
            }
            case 72: {
              int rawValue = input.readEnum();
              com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType value = com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(9, rawValue);
              } else {
                setEventType(value);
              }
              break;
            }
          }
        }
      }
      
      
      // optional sint32 callbackId = 1;
      public boolean hasCallbackId() {
        return result.hasCallbackId();
      }
      public int getCallbackId() {
        return result.getCallbackId();
      }
      public Builder setCallbackId(int value) {
        result.hasCallbackId = true;
        result.callbackId_ = value;
        return this;
      }
      public Builder clearCallbackId() {
        result.hasCallbackId = false;
        result.callbackId_ = 0;
        return this;
      }
      
      // optional bytes key = 2;
      public boolean hasKey() {
        return result.hasKey();
      }
      public com.google.protobuf.ByteString getKey() {
        return result.getKey();
      }
      public Builder setKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasKey = true;
        result.key_ = value;
        return this;
      }
      public Builder clearKey() {
        result.hasKey = false;
        result.key_ = getDefaultInstance().getKey();
        return this;
      }
      
      // optional int32 itemRemoveReason = 3;
      public boolean hasItemRemoveReason() {
        return result.hasItemRemoveReason();
      }
      public int getItemRemoveReason() {
        return result.getItemRemoveReason();
      }
      public Builder setItemRemoveReason(int value) {
        result.hasItemRemoveReason = true;
        result.itemRemoveReason_ = value;
        return this;
      }
      public Builder clearItemRemoveReason() {
        result.hasItemRemoveReason = false;
        result.itemRemoveReason_ = 0;
        return this;
      }
      
      // optional int32 flag = 4;
      public boolean hasFlag() {
        return result.hasFlag();
      }
      public int getFlag() {
        return result.getFlag();
      }
      public Builder setFlag(int value) {
        result.hasFlag = true;
        result.flag_ = value;
        return this;
      }
      public Builder clearFlag() {
        result.hasFlag = false;
        result.flag_ = 0;
        return this;
      }
      
      // repeated bytes value = 5;
      public java.util.List<com.google.protobuf.ByteString> getValueList() {
        return java.util.Collections.unmodifiableList(result.value_);
      }
      public int getValueCount() {
        return result.getValueCount();
      }
      public com.google.protobuf.ByteString getValue(int index) {
        return result.getValue(index);
      }
      public Builder setValue(int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.value_.set(index, value);
        return this;
      }
      public Builder addValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        result.value_.add(value);
        return this;
      }
      public Builder addAllValue(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
        }
        super.addAll(values, result.value_);
        return this;
      }
      public Builder clearValue() {
        result.value_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional .com.alachisoft.tayzgrid.common.protobuf.EventId eventId = 6;
      public boolean hasEventId() {
        return result.hasEventId();
      }
      public com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId getEventId() {
        return result.getEventId();
      }
      public Builder setEventId(com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEventId = true;
        result.eventId_ = value;
        return this;
      }
      public Builder setEventId(com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.Builder builderForValue) {
        result.hasEventId = true;
        result.eventId_ = builderForValue.build();
        return this;
      }
      public Builder mergeEventId(com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId value) {
        if (result.hasEventId() &&
            result.eventId_ != com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.getDefaultInstance()) {
          result.eventId_ =
            com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.newBuilder(result.eventId_).mergeFrom(value).buildPartial();
        } else {
          result.eventId_ = value;
        }
        result.hasEventId = true;
        return this;
      }
      public Builder clearEventId() {
        result.hasEventId = false;
        result.eventId_ = com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.EventId.getDefaultInstance();
        return this;
      }
      
      // optional int32 changeType = 7;
      public boolean hasChangeType() {
        return result.hasChangeType();
      }
      public int getChangeType() {
        return result.getChangeType();
      }
      public Builder setChangeType(int value) {
        result.hasChangeType = true;
        result.changeType_ = value;
        return this;
      }
      public Builder clearChangeType() {
        result.hasChangeType = false;
        result.changeType_ = 0;
        return this;
      }
      
      // optional string queryId = 8;
      public boolean hasQueryId() {
        return result.hasQueryId();
      }
      public java.lang.String getQueryId() {
        return result.getQueryId();
      }
      public Builder setQueryId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasQueryId = true;
        result.queryId_ = value;
        return this;
      }
      public Builder clearQueryId() {
        result.hasQueryId = false;
        result.queryId_ = getDefaultInstance().getQueryId();
        return this;
      }
      
      // optional .com.alachisoft.tayzgrid.common.protobuf.EventInfo.EventType eventType = 9;
      public boolean hasEventType() {
        return result.hasEventType();
      }
      public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType getEventType() {
        return result.getEventType();
      }
      public Builder setEventType(com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasEventType = true;
        result.eventType_ = value;
        return this;
      }
      public Builder clearEventType() {
        result.hasEventType = false;
        result.eventType_ = com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.EventType.ITEM_REMOVED_CALLBACK;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.EventInfo)
    }
    
    static {
      defaultInstance = new EventInfo(true);
      com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.EventInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017EventInfo.proto\022\'com.alachisoft.tayzgr" +
      "id.common.protobuf\032\rEventId.proto\"\277\003\n\tEv" +
      "entInfo\022\022\n\ncallbackId\030\001 \001(\021\022\013\n\003key\030\002 \001(\014" +
      "\022\030\n\020itemRemoveReason\030\003 \001(\005\022\014\n\004flag\030\004 \001(\005" +
      "\022\r\n\005value\030\005 \003(\014\022A\n\007eventId\030\006 \001(\01320.com.a" +
      "lachisoft.tayzgrid.common.protobuf.Event" +
      "Id\022\022\n\nchangeType\030\007 \001(\005\022\017\n\007queryId\030\010 \001(\t\022" +
      "O\n\teventType\030\t \001(\0162<.com.alachisoft.tayz" +
      "grid.common.protobuf.EventInfo.EventType" +
      "\"\240\001\n\tEventType\022\031\n\025ITEM_REMOVED_CALLBACK\020",
      "\001\022\031\n\025ITEM_UPDATED_CALLBACK\020\002\022\024\n\020ITEM_ADD" +
      "ED_EVENT\020\003\022\026\n\022ITEM_REMOVED_EVENT\020\004\022\026\n\022IT" +
      "EM_UPDATED_EVENT\020\005\022\027\n\023CACHE_CLEARED_EVEN" +
      "T\020\006B\023B\021EventInfoProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_EventInfo_descriptor,
              new java.lang.String[] { "CallbackId", "Key", "ItemRemoveReason", "Flag", "Value", "EventId", "ChangeType", "QueryId", "EventType", },
              com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.class,
              com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alachisoft.tayzgrid.common.protobuf.EventIdProtocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
