// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GroupEnumerationPointer.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class GroupEnumerationPointerProtocol {
  private GroupEnumerationPointerProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GroupEnumerationPointer extends
      com.google.protobuf.GeneratedMessage {
    // Use GroupEnumerationPointer.newBuilder() to construct.
    private GroupEnumerationPointer() {
      initFields();
    }
    private GroupEnumerationPointer(boolean noInit) {}
    
    private static final GroupEnumerationPointer defaultInstance;
    public static GroupEnumerationPointer getDefaultInstance() {
      return defaultInstance;
    }
    
    public GroupEnumerationPointer getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_fieldAccessorTable;
    }
    
    // optional sint32 chunkId = 1;
    public static final int CHUNKID_FIELD_NUMBER = 1;
    private boolean hasChunkId;
    private int chunkId_ = 0;
    public boolean hasChunkId() { return hasChunkId; }
    public int getChunkId() { return chunkId_; }
    
    // optional string id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private boolean hasId;
    private java.lang.String id_ = "";
    public boolean hasId() { return hasId; }
    public java.lang.String getId() { return id_; }
    
    // optional string group = 3;
    public static final int GROUP_FIELD_NUMBER = 3;
    private boolean hasGroup;
    private java.lang.String group_ = "";
    public boolean hasGroup() { return hasGroup; }
    public java.lang.String getGroup() { return group_; }
    
    // optional string subGroup = 4;
    public static final int SUBGROUP_FIELD_NUMBER = 4;
    private boolean hasSubGroup;
    private java.lang.String subGroup_ = "";
    public boolean hasSubGroup() { return hasSubGroup; }
    public java.lang.String getSubGroup() { return subGroup_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasChunkId()) {
        output.writeSInt32(1, getChunkId());
      }
      if (hasId()) {
        output.writeString(2, getId());
      }
      if (hasGroup()) {
        output.writeString(3, getGroup());
      }
      if (hasSubGroup()) {
        output.writeString(4, getSubGroup());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasChunkId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(1, getChunkId());
      }
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getId());
      }
      if (hasGroup()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getGroup());
      }
      if (hasSubGroup()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getSubGroup());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.getDefaultInstance()) return this;
        if (other.hasChunkId()) {
          setChunkId(other.getChunkId());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasGroup()) {
          setGroup(other.getGroup());
        }
        if (other.hasSubGroup()) {
          setSubGroup(other.getSubGroup());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setChunkId(input.readSInt32());
              break;
            }
            case 18: {
              setId(input.readString());
              break;
            }
            case 26: {
              setGroup(input.readString());
              break;
            }
            case 34: {
              setSubGroup(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional sint32 chunkId = 1;
      public boolean hasChunkId() {
        return result.hasChunkId();
      }
      public int getChunkId() {
        return result.getChunkId();
      }
      public Builder setChunkId(int value) {
        result.hasChunkId = true;
        result.chunkId_ = value;
        return this;
      }
      public Builder clearChunkId() {
        result.hasChunkId = false;
        result.chunkId_ = 0;
        return this;
      }
      
      // optional string id = 2;
      public boolean hasId() {
        return result.hasId();
      }
      public java.lang.String getId() {
        return result.getId();
      }
      public Builder setId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = getDefaultInstance().getId();
        return this;
      }
      
      // optional string group = 3;
      public boolean hasGroup() {
        return result.hasGroup();
      }
      public java.lang.String getGroup() {
        return result.getGroup();
      }
      public Builder setGroup(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasGroup = true;
        result.group_ = value;
        return this;
      }
      public Builder clearGroup() {
        result.hasGroup = false;
        result.group_ = getDefaultInstance().getGroup();
        return this;
      }
      
      // optional string subGroup = 4;
      public boolean hasSubGroup() {
        return result.hasSubGroup();
      }
      public java.lang.String getSubGroup() {
        return result.getSubGroup();
      }
      public Builder setSubGroup(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSubGroup = true;
        result.subGroup_ = value;
        return this;
      }
      public Builder clearSubGroup() {
        result.hasSubGroup = false;
        result.subGroup_ = getDefaultInstance().getSubGroup();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointer)
    }
    
    static {
      defaultInstance = new GroupEnumerationPointer(true);
      com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointer)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035GroupEnumerationPointer.proto\022\'com.ala" +
      "chisoft.tayzgrid.common.protobuf\"W\n\027Grou" +
      "pEnumerationPointer\022\017\n\007chunkId\030\001 \001(\021\022\n\n\002" +
      "id\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\020\n\010subGroup\030\004 \001(" +
      "\tB!B\037GroupEnumerationPointerProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_GroupEnumerationPointer_descriptor,
              new java.lang.String[] { "ChunkId", "Id", "Group", "SubGroup", },
              com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.class,
              com.alachisoft.tayzgrid.common.protobuf.GroupEnumerationPointerProtocol.GroupEnumerationPointer.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
