// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RegisterKeyNotifResponse.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class RegisterKeyNotifResponseProtocol {
  private RegisterKeyNotifResponseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RegisterKeyNotifResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RegisterKeyNotifResponse.newBuilder() to construct.
    private RegisterKeyNotifResponse() {
      initFields();
    }
    private RegisterKeyNotifResponse(boolean noInit) {}
    
    private static final RegisterKeyNotifResponse defaultInstance;
    public static RegisterKeyNotifResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RegisterKeyNotifResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponse)
    }
    
    static {
      defaultInstance = new RegisterKeyNotifResponse(true);
      com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036RegisterKeyNotifResponse.proto\022\'com.al" +
      "achisoft.tayzgrid.common.protobuf\"\032\n\030Reg" +
      "isterKeyNotifResponseB\"B RegisterKeyNoti" +
      "fResponseProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_RegisterKeyNotifResponse_descriptor,
              new java.lang.String[] { },
              com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.class,
              com.alachisoft.tayzgrid.common.protobuf.RegisterKeyNotifResponseProtocol.RegisterKeyNotifResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
