// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShutDownServerInfo.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class ShutDownServerInfoProtocol {
  private ShutDownServerInfoProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class ShutDownServerInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use ShutDownServerInfo.newBuilder() to construct.
    private ShutDownServerInfo() {
      initFields();
    }
    private ShutDownServerInfo(boolean noInit) {}
    
    private static final ShutDownServerInfo defaultInstance;
    public static ShutDownServerInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public ShutDownServerInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_fieldAccessorTable;
    }
    
    // optional string serverIP = 1;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private boolean hasServerIP;
    private java.lang.String serverIP_ = "";
    public boolean hasServerIP() { return hasServerIP; }
    public java.lang.String getServerIP() { return serverIP_; }
    
    // optional int64 timeoutInterval = 2;
    public static final int TIMEOUTINTERVAL_FIELD_NUMBER = 2;
    private boolean hasTimeoutInterval;
    private long timeoutInterval_ = 0L;
    public boolean hasTimeoutInterval() { return hasTimeoutInterval; }
    public long getTimeoutInterval() { return timeoutInterval_; }
    
    // optional string uniqueKey = 3;
    public static final int UNIQUEKEY_FIELD_NUMBER = 3;
    private boolean hasUniqueKey;
    private java.lang.String uniqueKey_ = "";
    public boolean hasUniqueKey() { return hasUniqueKey; }
    public java.lang.String getUniqueKey() { return uniqueKey_; }
    
    // optional int32 port = 4;
    public static final int PORT_FIELD_NUMBER = 4;
    private boolean hasPort;
    private int port_ = 0;
    public boolean hasPort() { return hasPort; }
    public int getPort() { return port_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasServerIP()) {
        output.writeString(1, getServerIP());
      }
      if (hasTimeoutInterval()) {
        output.writeInt64(2, getTimeoutInterval());
      }
      if (hasUniqueKey()) {
        output.writeString(3, getUniqueKey());
      }
      if (hasPort()) {
        output.writeInt32(4, getPort());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasServerIP()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getServerIP());
      }
      if (hasTimeoutInterval()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, getTimeoutInterval());
      }
      if (hasUniqueKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getUniqueKey());
      }
      if (hasPort()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getPort());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.getDefaultInstance()) return this;
        if (other.hasServerIP()) {
          setServerIP(other.getServerIP());
        }
        if (other.hasTimeoutInterval()) {
          setTimeoutInterval(other.getTimeoutInterval());
        }
        if (other.hasUniqueKey()) {
          setUniqueKey(other.getUniqueKey());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setServerIP(input.readString());
              break;
            }
            case 16: {
              setTimeoutInterval(input.readInt64());
              break;
            }
            case 26: {
              setUniqueKey(input.readString());
              break;
            }
            case 32: {
              setPort(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string serverIP = 1;
      public boolean hasServerIP() {
        return result.hasServerIP();
      }
      public java.lang.String getServerIP() {
        return result.getServerIP();
      }
      public Builder setServerIP(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServerIP = true;
        result.serverIP_ = value;
        return this;
      }
      public Builder clearServerIP() {
        result.hasServerIP = false;
        result.serverIP_ = getDefaultInstance().getServerIP();
        return this;
      }
      
      // optional int64 timeoutInterval = 2;
      public boolean hasTimeoutInterval() {
        return result.hasTimeoutInterval();
      }
      public long getTimeoutInterval() {
        return result.getTimeoutInterval();
      }
      public Builder setTimeoutInterval(long value) {
        result.hasTimeoutInterval = true;
        result.timeoutInterval_ = value;
        return this;
      }
      public Builder clearTimeoutInterval() {
        result.hasTimeoutInterval = false;
        result.timeoutInterval_ = 0L;
        return this;
      }
      
      // optional string uniqueKey = 3;
      public boolean hasUniqueKey() {
        return result.hasUniqueKey();
      }
      public java.lang.String getUniqueKey() {
        return result.getUniqueKey();
      }
      public Builder setUniqueKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUniqueKey = true;
        result.uniqueKey_ = value;
        return this;
      }
      public Builder clearUniqueKey() {
        result.hasUniqueKey = false;
        result.uniqueKey_ = getDefaultInstance().getUniqueKey();
        return this;
      }
      
      // optional int32 port = 4;
      public boolean hasPort() {
        return result.hasPort();
      }
      public int getPort() {
        return result.getPort();
      }
      public Builder setPort(int value) {
        result.hasPort = true;
        result.port_ = value;
        return this;
      }
      public Builder clearPort() {
        result.hasPort = false;
        result.port_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfo)
    }
    
    static {
      defaultInstance = new ShutDownServerInfo(true);
      com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030ShutDownServerInfo.proto\022\'com.alachiso" +
      "ft.tayzgrid.common.protobuf\"`\n\022ShutDownS" +
      "erverInfo\022\020\n\010serverIP\030\001 \001(\t\022\027\n\017timeoutIn" +
      "terval\030\002 \001(\003\022\021\n\tuniqueKey\030\003 \001(\t\022\014\n\004port\030" +
      "\004 \001(\005B\034B\032ShutDownServerInfoProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_ShutDownServerInfo_descriptor,
              new java.lang.String[] { "ServerIP", "TimeoutInterval", "UniqueKey", "Port", },
              com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.class,
              com.alachisoft.tayzgrid.common.protobuf.ShutDownServerInfoProtocol.ShutDownServerInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
