// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SyncEventsResponse.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class SyncEventsResponseProtocol {
  private SyncEventsResponseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SyncEventsResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SyncEventsResponse.newBuilder() to construct.
    private SyncEventsResponse() {
      initFields();
    }
    private SyncEventsResponse(boolean noInit) {}
    
    private static final SyncEventsResponse defaultInstance;
    public static SyncEventsResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SyncEventsResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_fieldAccessorTable;
    }
    
    // repeated .com.alachisoft.tayzgrid.common.protobuf.EventInfo eventInfo = 1;
    public static final int EVENTINFO_FIELD_NUMBER = 1;
    private java.util.List<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo> eventInfo_ =
      java.util.Collections.emptyList();
    public java.util.List<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo> getEventInfoList() {
      return eventInfo_;
    }
    public int getEventInfoCount() { return eventInfo_.size(); }
    public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo getEventInfo(int index) {
      return eventInfo_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo element : getEventInfoList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo element : getEventInfoList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.eventInfo_ != java.util.Collections.EMPTY_LIST) {
          result.eventInfo_ =
            java.util.Collections.unmodifiableList(result.eventInfo_);
        }
        com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.getDefaultInstance()) return this;
        if (!other.eventInfo_.isEmpty()) {
          if (result.eventInfo_.isEmpty()) {
            result.eventInfo_ = new java.util.ArrayList<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo>();
          }
          result.eventInfo_.addAll(other.eventInfo_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.Builder subBuilder = com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addEventInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.alachisoft.tayzgrid.common.protobuf.EventInfo eventInfo = 1;
      public java.util.List<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo> getEventInfoList() {
        return java.util.Collections.unmodifiableList(result.eventInfo_);
      }
      public int getEventInfoCount() {
        return result.getEventInfoCount();
      }
      public com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo getEventInfo(int index) {
        return result.getEventInfo(index);
      }
      public Builder setEventInfo(int index, com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.eventInfo_.set(index, value);
        return this;
      }
      public Builder setEventInfo(int index, com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.Builder builderForValue) {
        result.eventInfo_.set(index, builderForValue.build());
        return this;
      }
      public Builder addEventInfo(com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.eventInfo_.isEmpty()) {
          result.eventInfo_ = new java.util.ArrayList<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo>();
        }
        result.eventInfo_.add(value);
        return this;
      }
      public Builder addEventInfo(com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo.Builder builderForValue) {
        if (result.eventInfo_.isEmpty()) {
          result.eventInfo_ = new java.util.ArrayList<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo>();
        }
        result.eventInfo_.add(builderForValue.build());
        return this;
      }
      public Builder addAllEventInfo(
          java.lang.Iterable<? extends com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo> values) {
        if (result.eventInfo_.isEmpty()) {
          result.eventInfo_ = new java.util.ArrayList<com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.EventInfo>();
        }
        super.addAll(values, result.eventInfo_);
        return this;
      }
      public Builder clearEventInfo() {
        result.eventInfo_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponse)
    }
    
    static {
      defaultInstance = new SyncEventsResponse(true);
      com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030SyncEventsResponse.proto\022\'com.alachiso" +
      "ft.tayzgrid.common.protobuf\032\017EventInfo.p" +
      "roto\"[\n\022SyncEventsResponse\022E\n\teventInfo\030" +
      "\001 \003(\01322.com.alachisoft.tayzgrid.common.p" +
      "rotobuf.EventInfoB\034B\032SyncEventsResponseP" +
      "rotocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_SyncEventsResponse_descriptor,
              new java.lang.String[] { "EventInfo", },
              com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.class,
              com.alachisoft.tayzgrid.common.protobuf.SyncEventsResponseProtocol.SyncEventsResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.alachisoft.tayzgrid.common.protobuf.EventInfoProtocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
