// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TagInfo.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class TagInfoProtocol {
  private TagInfoProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TagInfo extends
      com.google.protobuf.GeneratedMessage {
    // Use TagInfo.newBuilder() to construct.
    private TagInfo() {
      initFields();
    }
    private TagInfo(boolean noInit) {}
    
    private static final TagInfo defaultInstance;
    public static TagInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public TagInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_fieldAccessorTable;
    }
    
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // repeated string tags = 2;
    public static final int TAGS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.String> tags_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getTagsList() {
      return tags_;
    }
    public int getTagsCount() { return tags_.size(); }
    public java.lang.String getTags(int index) {
      return tags_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeString(1, getType());
      }
      for (java.lang.String element : getTagsList()) {
        output.writeString(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getType());
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getTagsList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getTagsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.tags_ != java.util.Collections.EMPTY_LIST) {
          result.tags_ =
            java.util.Collections.unmodifiableList(result.tags_);
        }
        com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (!other.tags_.isEmpty()) {
          if (result.tags_.isEmpty()) {
            result.tags_ = new java.util.ArrayList<java.lang.String>();
          }
          result.tags_.addAll(other.tags_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setType(input.readString());
              break;
            }
            case 18: {
              addTags(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // repeated string tags = 2;
      public java.util.List<java.lang.String> getTagsList() {
        return java.util.Collections.unmodifiableList(result.tags_);
      }
      public int getTagsCount() {
        return result.getTagsCount();
      }
      public java.lang.String getTags(int index) {
        return result.getTags(index);
      }
      public Builder setTags(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.tags_.set(index, value);
        return this;
      }
      public Builder addTags(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.tags_.isEmpty()) {
          result.tags_ = new java.util.ArrayList<java.lang.String>();
        }
        result.tags_.add(value);
        return this;
      }
      public Builder addAllTags(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.tags_.isEmpty()) {
          result.tags_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.tags_);
        return this;
      }
      public Builder clearTags() {
        result.tags_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.TagInfo)
    }
    
    static {
      defaultInstance = new TagInfo(true);
      com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.TagInfo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rTagInfo.proto\022\'com.alachisoft.tayzgrid" +
      ".common.protobuf\"%\n\007TagInfo\022\014\n\004type\030\001 \001(" +
      "\t\022\014\n\004tags\030\002 \003(\tB\021B\017TagInfoProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_TagInfo_descriptor,
              new java.lang.String[] { "Type", "Tags", },
              com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.class,
              com.alachisoft.tayzgrid.common.protobuf.TagInfoProtocol.TagInfo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
