// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TaskProgressResponse.proto

package com.alachisoft.tayzgrid.common.protobuf;

public final class TaskProgressResponseProtocol {
  private TaskProgressResponseProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TaskProgressResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use TaskProgressResponse.newBuilder() to construct.
    private TaskProgressResponse() {
      initFields();
    }
    private TaskProgressResponse(boolean noInit) {}
    
    private static final TaskProgressResponse defaultInstance;
    public static TaskProgressResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TaskProgressResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_fieldAccessorTable;
    }
    
    // optional bytes progresses = 1;
    public static final int PROGRESSES_FIELD_NUMBER = 1;
    private boolean hasProgresses;
    private com.google.protobuf.ByteString progresses_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasProgresses() { return hasProgresses; }
    public com.google.protobuf.ByteString getProgresses() { return progresses_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasProgresses()) {
        output.writeBytes(1, getProgresses());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasProgresses()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getProgresses());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse result;
      
      // Construct using com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse();
        return builder;
      }
      
      protected com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.getDescriptor();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse getDefaultInstanceForType() {
        return com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse) {
          return mergeFrom((com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse other) {
        if (other == com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.getDefaultInstance()) return this;
        if (other.hasProgresses()) {
          setProgresses(other.getProgresses());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setProgresses(input.readBytes());
              break;
            }
          }
        }
      }
      
      
      // optional bytes progresses = 1;
      public boolean hasProgresses() {
        return result.hasProgresses();
      }
      public com.google.protobuf.ByteString getProgresses() {
        return result.getProgresses();
      }
      public Builder setProgresses(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProgresses = true;
        result.progresses_ = value;
        return this;
      }
      public Builder clearProgresses() {
        result.hasProgresses = false;
        result.progresses_ = getDefaultInstance().getProgresses();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponse)
    }
    
    static {
      defaultInstance = new TaskProgressResponse(true);
      com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032TaskProgressResponse.proto\022\'com.alachi" +
      "soft.tayzgrid.common.protobuf\"*\n\024TaskPro" +
      "gressResponse\022\022\n\nprogresses\030\001 \001(\014B\036B\034Tas" +
      "kProgressResponseProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_alachisoft_tayzgrid_common_protobuf_TaskProgressResponse_descriptor,
              new java.lang.String[] { "Progresses", },
              com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.class,
              com.alachisoft.tayzgrid.common.protobuf.TaskProgressResponseProtocol.TaskProgressResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
